collections:
  - name: amazon.aws
    version: "10.1.2"
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "11.4.1"
  # add when you start using k8s modules
  # - name: kubernetes.core
  #   version: "6.2.0"
